### ISSUE TITLE
Some random improvements

### ISSUE THREAD

**Issue by don-smith** [shekhargulati/hands-on-serverless-guide#7]
First, let me thank you for publishing this. I'm finding it very helpful as I'm currently building an app with Serverless, Lambda and DynamoDB.

As I've been going through this, I've been making some edits in my fork. If you're interested, I'm happy to submit a pull request to you. You can see the changes I've made so far [here](https://github.com/shekhargulati/hands-on-serverless-guide/compare/master...don-smith:random-improvements?expand=1). Just let me know.

Thanks again! 👍

**Comment by shekhargulati** [comment]
Glad that you found it useful. @don-smith please send PR with your changes. Your changes will help improve quality of the guide. 

Thanks.

**Comment by shekhargulati** [comment]
Hello @don-smith still waiting for your PR -:)

**Comment by don-smith** [comment]
Sorry about the delay @shekhargulati. I got pulled away onto another project. I'll go ahead and send a PR for what I've reviewed so far (instead of waiting until I'm done with all of it) and submit a second one for the rest.
